name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/dduportal/esgi-gitpod
      options: --user=root
    steps:
      - uses: actions/checkout@v3

      - name: Lint Dockerfile with hadolint
        run: hadolint ./Dockerfile

      - run: npm install
      - run: npm run lint
